### ISSUE TITLE
Recognition of numbers.

### ISSUE THREAD

**Issue by julienfadel** [eelretep/HandwritingTextField#4]
The app is not able to recognize number's. For example, if you write 22 it will give you ss. I have tried with 200, 22, 31, 40. It is not able to recognize any number.

Although, it recognizes one number at a time, for example if I write 2, it will give me 2.

**Comment by Amir-OffsureIt** [comment]
Any update on this issue?

**Comment by Amir-OffsureIt** [comment]
> The app is not able to recognize number's. For example, if you write 22 it will give you ss. I have tried with 200, 22, 31, 40. It is not able to recognize any number.
> 
> Although, it recognizes one number at a time, for example if I write 2, it will give me 2.

I'm facing the same issue

**Comment by eelretep** [comment]
I think it's just finicky about multiple numbers. I got 22 to work eventually, but the google endpoint definitely seems to favor alpha over numeric interpretations when there are multiple characters.

![screen shot 2019-02-28 at 9 10 25 am](https://user-images.githubusercontent.com/2941455/53584689-0552d500-3b39-11e9-9120-ef1324c0cfd4.png)
